## Softmax Classification
+ 텐서플로우로 짜보기
------

In [2]:
import tensorflow as tf
import numpy as np

tf.random.set_seed(1)

# X : 8X4 행렬, Y : 8X3 행렬
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3 # Y 결과값의 개수

print(f"x_data : {x_data.shape}\ny_data : {y_data.shape}")

x_data : (8, 4)
y_data : (8, 3)


In [3]:
W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

print(variables)

[<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-1.1012203 ,  1.5457517 ,  0.383644  ],
       [-0.87965786, -1.2246722 , -0.9811211 ],
       [ 0.08780783, -0.20326038, -0.5581562 ],
       [-0.72054404, -0.6259924 , -0.71502596]], dtype=float32)>, <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 0.40308788, -1.0880208 , -0.06309535], dtype=float32)>]


In [4]:
# Softmax regression을 통한 hypothesis
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[2.8565836e-01 3.7394714e-01 3.4039453e-01]
 [5.3687010e-02 8.5996407e-01 8.6348981e-02]
 [3.5553419e-03 9.7092170e-01 2.5522944e-02]
 [4.2082451e-04 9.9589503e-01 3.6841528e-03]
 [8.6085868e-01 9.1479145e-02 4.7662225e-02]
 [5.7206035e-01 3.7504578e-01 5.2893914e-02]
 [8.6537075e-01 1.0668017e-01 2.7949085e-02]
 [9.1987038e-01 6.5981895e-02 1.4147687e-02]], shape=(8, 3), dtype=float32)


In [6]:
# ?? 왜 Softmax onehot test가 중간에 있는거지?
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[5.1618025e-09 9.9979573e-01 2.0427014e-04]], shape=(1, 3), dtype=float32)


### reduce_sum과 reduce_mean에서 axis
#####       axis=0은 행렬의 첫번째 축, 즉 세로의 값들을 평균을 내고 axis=1는 행렬의 두번째 축, 즉 가로의 값들을 평균을 낸다는 의미
+ print(cost) with axis = 0
+ tf.Tensor([0.22811976 3.3764648  7.1951857 ], shape=(3,), dtype=float32)
+ print(cost) with axis = 1
+ tf.Tensor([1.07765    2.4493582  3.6681776  0.00411342 2.3916442  0.98070717 0.14459725 0.08352251], shape=(8,), dtype=float32)

In [17]:
# Cost function using cross-entropy
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(
[1.07765    2.4493582  3.6681776  0.00411342 2.3916442  0.98070717
 0.14459725 0.08352251], shape=(8,), dtype=float32)
tf.Tensor(1.3499713, shape=(), dtype=float32)


In [ ]:
x = tf.constant(3.0)
